Function New-ModuleTemplate
{
	PARAM([Parameter(Mandatory=$true)]
		  [string]$ProcessName
        , [string]$description
        , [Parameter(Mandatory=$true,position=0)] 
		  [AllowNull()] 
		  [AllowEmptyCollection()] 
		  [Tags[]] $tags
        , [string]$orgName
        , [string]$codePath)

	if ($codePath)
	{
		$newPath = Join-Path $codePath -ChildPath "Modules\$ProcessName"
	}
	else 
	{
		$newPath = Join-Path (Get-item $PSScriptRoot).parent.parent.parent.Fullname -ChildPath $ProcessName
	}


    Write-host $newPath

    If (Test-path -Path $newpath)
    {
        Write-Error "Module $ProcessName already exists" -ErrorAction Stop
    }

    $folders = @("$ProcessName\public", "$ProcessName\private", 'tests\integration', 'tests\unit')
    $folders | ForEach-Object {New-Item -Path (Join-Path $newPath -ChildPath $_) -ItemType Directory -Force} | Out-Null

    $psakeText = @"
<#
.DESCRIPTION
psake 'make' file to pull all module requirements together and run all required tests.
#>
Properties {
	`$projectRoot = `$PSScriptRoot
	"Project root: `$projectRoot"

    `$moduleRoot = Split-Path (Resolve-Path "`$projectRoot\*\*.psm1")
	`$moduleName = Split-Path `$moduleRoot -Leaf

	`$timestamp = Get-date -uformat "%Y%m%d-%H%M%S"
	`$PSVersion = `$PSVersionTable.PSVersion.Major
	`$testFile = "TestResults_PS`$PSVersion``_`$timeStamp.xml"
	`$separator = '----------------------------------------------------------------------'
	`$verbose = @{Verbose = `$True}
}

Task Default -Depends HelpTests

Task Init {
	`$separator
	Set-Location `$projectRoot
	"``n"
}

Task ProjectTests -Depends Init {
	`$separator
	"STATUS: Testing with PowerShell `$PSVersion``n"

	`$testResults = Invoke-Pester -Path "`$projectRoot\tests\*project*" -PassThru -Tag Build

	if (`$testResults.FailedCount -gt 0) {
		`$testResults | Format-List
		Write-Error "Failed '`$(`$testResults.FailedCount)' tests, build failed"
	}
	"``n"
}

Task UnitTests -Depends ProjectTests {
	`$separator

	`$testResults = Invoke-Pester -Path "`$projectRoot\tests\*unit*" -PassThru -Tag Build

	if (`$testResults.FailedCount -gt 0) {
		`$testResults | Format-List
		Write-Error "Failed '`$(`$testResults.FailedCount)' tests, build failed"
	}
	"``n"
}

Task HelpTests -Depends UnitTests {
	`$separator

	`$testResults = Invoke-Pester -Path "`$projectRoot\tests\*help*" -PassThru -Tag Build

	if (`$testResults.FailedCount -gt 0) {
		`$testResults | Format-List
		Write-Error "Failed '`$(`$testResults.FailedCount)' tests, build failed"
	}
	"``n"
}
"@

    $psakeText | Out-File -FilePath (Join-Path $newPath -ChildPath 'psake.ps1') -Force | Out-Null

    $psdText = @"
#
# Module manifest for module '$ProcessName'
#
# Generated by: $($ENV:Username.ToUpper())
#
# Generated on: $(Get-date -Format 'MM/dd/yyyy')
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '$ProcessName.psm1'

# Version number of this module.
ModuleVersion = '0.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '$((New-Guid).GUID)'

# Author of this module
Author = '$($ENV:Username.ToUpper())'

# Company or vendor of this module
CompanyName = '$orgName'

# Copyright statement for this module
Copyright = '(c) $(get-date -Format yyyy) $orgName. All rights reserved.'

# Description of the functionality provided by this module
Description = '$description'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
# NOTE - this is commented out because Export-ModuleMember is being used instead
# FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @($($tags -join ","))

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
"@

    $psmText = @"
#Requires -Version 3.0
[CmdletBinding()]
Param()

####################################################################################
## Dynamic module loader - can be used without changes for any PowerShell module
## All function files must be in 'public' or 'private' child directories.
####################################################################################

Write-Verbose "Loading production scripts from public and private module directories..."

if (`$PSScriptRoot)
{
    `$scriptPath = `$PSScriptRoot
}
else
{
    `$scriptPath = Get-Location
}

# Dot-source each private and public script file to load it (must not have '.Test*' in the name)
`$privatePath = (Join-Path -Path `$scriptPath -ChildPath 'private')
`$publicPath  = (Join-Path -Path `$scriptPath -ChildPath 'public')

if (Test-Path -Path `$privatePath -PathType Container)
{
	`$privateScriptFiles = (Get-ChildItem -Path `$privatePath -Filter *.ps1 -Recurse) |
		Where { `$_.name -NotLike '*.Test*.ps1' }

	`$privateScriptFiles | ForEach {
			Write-Verbose ('Loading private function {0}' -f `$_.basename)
			. `$_.FullName
		}
}

if (Test-Path -Path `$publicPath -PathType Container)
{
	`$publicScriptFiles = (Get-ChildItem -Path `$publicPath -Filter *.ps1 -Recurse) |
		Where { `$_.name -NotLike '*.Test*.ps1' }

	`$publicScriptFiles | ForEach {
			Write-Verbose ('Loading public function {0}' -f `$_.basename)
			. `$_.FullName
		}
}
else
{
	Write-Error "Damaged module: 'public' directory is missing from the script install directory '`$scriptPath'"
}

# Export only public module functions
foreach (`$publicScriptFile in `$publicScriptFiles) { Export-ModuleMember -Function `$publicScriptFile.basename }

"@

    $ScriptPath = Join-Path $newPath -ChildPath $ProcessName
    $psdText | Out-File -FilePath (Join-Path $ScriptPath -ChildPath "$ProcessName.psd1") -Force | Out-Null
	$psmText | Out-File -FilePath (Join-Path $ScriptPath -ChildPath "$ProcessName.psm1") -Force | Out-Null
	
	Write-Verbose "Module created! Check the following path: $newPath"
}
