trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module xanderu.helpers -force
      Import-Module xanderu.helpers
      Publish-ToPSGallery -PSGalleryKey $(PSGalleryKey) `
                          -secureRepoName 'PowershellAZDO' `
                          -secureRepopublishApiKey $(AZDOPat) `
                          -secureRepopublishApiURL "https://pkgs.dev.azure.com/xanderu/master/_packaging/PSRepo/nuget/v2/" `
                          -secureRepoUser $(emailAddr) `
                          -secureRepoPass $(AZDOPat) `
                          -codePath $(Build.Repository.LocalPath)