trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module xanderu.helpers -force
      Import-Module xanderu.helpers
      # reference for keys/tokens https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops
      Publish-ToPSGallery -codePath $(Build.Repository.LocalPath) -PSGalleryKey $(PSGalleryKey) -secureRepoName 'PowershellAZDO' -secureRepoURI "https://pkgs.dev.azure.com/alexrudolph1987/xanderu/_packaging/PSRepo/nuget/v2" -secureRepopublishApiKey "az https://pkgs.dev.azure.com/alexrudolph1987/_packaging/alexrudolph1987/nuget/v3/index.json" -secureRepoUser $(emailAddr) -secureRepoPass  $(AZDOPat)