trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo $(Build.Repository.LocalPath)
- bash: echo $(Build.SourcesDirectory)

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module xanderu.helpers -force
      Import-Module xanderu.helpers
      Publish-ToPSGallery -codePath $(Build.Repository.LocalPath) -PSGalleryKey $(PSGalleryKey) 